const ActionTypes = {
    GET_MENU_DATA:          "GET_MENU_DATA",
    GET_CAR_DAMAGE:         "GET_CAR_DAMAGE",
    GET_CAR_DETAILS:        "GET_CAR_DETAILS",
    PUT_CAR_DETAILS:        "PUT_CAR_DETAILS",
    GET_CAR_DAMAGE_API:     "GET_CAR_DAMAGE_API",
    ADD_CAR_DAMAGE_DETAILS: "ADD_CAR_DAMAGE_DETAILS",
    GET_CAR_ALL_INFORMATION: "GET_CAR_ALL_INFORMATION"
}


export default ActionTypes